### ISSUE TITLE
Versioning and Install issues

### ISSUE THREAD

**Issue by Goobley** [OfAaron3/irispreppy#1]
The current pip version tries to get beautiful soup through `bs4` (which fails on most python), and the current tree goes for [`beatifulsoup4`](https://github.com/OfAaron3/irispreppy/blob/641ed10787e3610ddbc1e8e1269beb0755735705/setup.py#L20) (typo).
Try and sort the astropy requirements too? Is there an issue with >v4.2.0 ?

**Comment by OfAaron3** [comment]
The requirement of astropy<4.2.0 has been removed.
The "beatifulsoup4" issue has also been resolved.
