### ISSUE TITLE
Combination of HDU and `save=True` arguments to radiometric calibration

### ISSUE THREAD

**Issue by Goobley** [OfAaron3/irispreppy#2]
If an HDU is passed instead of a str containing a path, the code will attempt `fitsHdu[-5:] + '_rc.fits'`. Which is an issue that should be checked somewhere. This is likely an issue if a list is passed too.

**Comment by OfAaron3** [comment]
This has been fixed by getting the filename from the astropy fits object and not a string. It was a very hacky approach to be fair.
